name: CI

on:
  workflow_dispatch:

jobs:
  sign:
    runs-on: macos-latest
    env:
      SECRET_URL: "${{ http://chimera-jailbreak.com/ }}"
      SECRET_KEY: "${{ ABCDEFG1234 }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sign
        run: |
          ./sign.sh
